services:
  web:
    build: .
    container_name: ipb-preloved-web
    ports:
      - "8788:8788"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    # Wrangler akan baca .dev.vars otomatis di dalam container
    environment:
      - NODE_ENV=development
      # - DB_RESET=true  # Hapus tanda '#' di awal untuk paksa RESET database saat startup
    stdin_open: true
    tty: true
    restart: unless-stopped
