name = "ipb-preloved"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB" # Ini nama variabel yang bakal kita panggil di code
database_name = "ipb-preloved-db"
database_id = "777ac36d-0a4f-4996-9c38-201fed833d73"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ipb-preloved-images"